// Generated by CoffeeScript 1.9.3
if (typeof RikkiTikki === "undefined" || RikkiTikki === null) {
  throw console.log("ApiHero not found -- insure it is isntalled nd added to your JS stack");
}

RikkiTikki.extend(ApiHero);
