// Generated by CoffeeScript 1.9.3
var WebSock, connection, io, io_redis;

io_redis = require('socket.io-redis');

io = require('socket.io');

connection = require('./client/connection');

WebSock = {};

WebSock.StreamModel = require('./models/stream-model');

WebSock.StreamCollection = require('./models/stream-collection');

WebSock.Client = require('./client');

module.exports.WebSock = WebSock;

module.exports.init = (function(_this) {
  return function(app, options, callback) {
    var opts, server;
    opts = _.extend({}, {
      auto_connect: true,
      redisHost: 'localhost',
      redisPort: 6379,
      secure: false
    }, options);
    server = require(opts.secure ? 'https' : 'http').Server(app);
    if (!app.hasOwnProperty('APIHero' && typeof app.APIHero === 'object')) {
      console.log('APIHero not found\ntry running: npm install --save apihero');
      process.exit(1);
    }
    app.APIHero.io = io(server);
    app.APIHero.io.adapter(redis({
      host: opts.redisHost,
      port: opts.redisPort
    }));
    return process.nextTick(callback);
  };
})(this);
