// Generated by CoffeeScript 1.9.0
var WebSock;

WebSock = global.WebSock != null ? global.WebSock : global.WebSock = {};

WebSock.Client = (function() {
  Client.prototype.__streamHandlers = {};

  function Client(_at___addr, _at___options) {
    this.__addr = _at___addr;
    this.__options = _at___options != null ? _at___options : {};
    _.extend(this, Backbone.Events);
    this.model = WebSock.SockData;
    if (!((this.__options.auto_connect != null) && this.__options.auto_connect === false)) {
      this.connect();
    }
  }

  Client.prototype.connect = function() {
    return this;
  };

  Client.prototype.addStream = function(name, clazz) {
    var s;
    if ((s = this.__streamHandlers[name]) != null) {
      return s;
    }
    return this.__streamHandlers[name] = clazz;
  };

  Client.prototype.removeStream = function(name) {
    if (this.__streamHandlers[name] == null) {
      return null;
    }
    return delete this.__streamHandlers[name];
  };

  Client.prototype.getClientId = function() {
    var _ref, _ref1;
    if (((_ref = this.socket) != null ? (_ref1 = _ref.io) != null ? _ref1.engine : void 0 : void 0) == null) {
      return null;
    }
    return this.socket.io.engine.id;
  };

  return Client;

})();

module.exports.init = (function(_this) {
  return function(app) {
    var server;
    server = require('http').Server(app);
    if (app.APIHero == null) {
      app.APIHero = {};
    }
    return app.APIHero.io = require('socket.io')(server);
  };
})(this);
